<a href="https://colab.research.google.com/github/alimovscott/ai-foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install numpy

In [ ]:
import numpy as np

In [1]:
# 1D array

import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

numpy_array: [1 3 5 7]


In [3]:
# 2D array -> matrix
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array2:', arr2)

arr2.shape

numpy_array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [4]:
# dtype
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [5]:
# reshape()

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print("shaped_array:", b)


shaped_array: [[1 2 3]
 [4 5 6]]


In [6]:
#  astype()

a = np.array([1, 2, 3])
b = a.astype(float)

print("float:", b)

float: [1. 2. 3.]


In [ ]:
# np.zeros(), np.ones() => dummy data

z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

In [ ]:
# ndim => used to find dimension

a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

In [ ]:
# arange() => used to create array for test data

a = np.arange(1, 6)

print("arange:", a)

In [ ]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum: ", a.sum())
print("mean: ", a.mean())
print("max: ", a.max())
print("min: ", a.min())

In [ ]:
# flatten() => 2D/3D -> into 1D array

a = np.array([[1, 2], [3, 4]])
b = a.flatten()

print("flatten:", b)


In [ ]:
# T (Transpose)

a = np.array([[1, 2], [3, 4]])
print("transpose: ", a.T)

In [ ]:
# dot() - @ (Matrix maltiplication)

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

# print("dot/maltiplication: ", a.dot(b))
print("dot/maltiplication: ", a @ b)

In [7]:
# random.rand() - creates random numbers between [0, 1)

a = np.random.rand(2, 3)
print("random: ", a)

random:  [[0.86024867 0.85797135 0.50386195]
 [0.65650232 0.60922738 0.23441089]]
